# Project Configuration
config:
  project_name: "zlib"
  program_language: "c++"
  fuzz_projects_dir: "/CKGFuzzer/fuzzing_llm_engine/external_database/zlib/"
  work_dir: "/CKGFuzzer/"
  shared_dir: "/CKGFuzzer/docker_shared/"
  report_target_dir: "/linux/src/zlib/"
  time_budget: "5m"

  headers:
    - "zlib.h"
    - <stdlib.h>
    - <string.h>
    - <stdint.h>
    - <sstream>
  

llm_embedding:


# DeepSeek Analyzer Configuration
llm_analyzer:
  api_key: ""
  model: "deepseek-chat"
  #proxy: "http://<ip>:<port>"
  base_url: "https://api.deepseek.com/v1"
  temperature: 1.0


# DeepSeek Coder Configuration
llm_coder:
  api_key: ""
  model: "deepseek-coder"
  #proxy: "http://<ip>:<port>"
  base_url: "https://api.deepseek.com/v1"
  temperature: 0.7

