homepage: "https://www.webmproject.org"
language: c++
primary_contact: "jzern@google.com"
sanitizers:
- address
- memory
- undefined
auto_ccs:
- jianj@google.com
- jingning@google.com
- jzern@google.com
- wtc@google.com
vendor_ccs:
- twsmith@mozilla.com
main_repo: 'https://chromium.googlesource.com/webm/libvpx'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

